name: 'Upload production artefact (not publish)'
description: 'Upload production artefact (not publish)'
inputs:
  upload_prefix:
    description: 'upload name prefix'
    required: true
  multiarch_build:
    description: 'build folder contains multiple architectures'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Remove unpacked files
      run: |
        ls -d -- */ | xargs -I{} echo "Removing {}"
        ls -d -- */ | xargs -I{} rm -rf {}
      shell: bash
      working-directory: ./release/

    - name: Make artefacts folder
      run: mkdir -p ${{ inputs.upload_prefix }}-production
      shell: bash
      working-directory: ./release/

    - name: Move all files
      if: ${{ inputs.multiarch_build == 'false' }}
      run: |
        ls -p | grep -v / | xargs -I{} mv {} ${{ inputs.upload_prefix }}-production/
      shell: bash
      working-directory: ./release/

    - name: Move ${{ inputs.upload_prefix }} files
      if: ${{ inputs.multiarch_build == 'true' }}
      run: |
        ls -p | grep -v / | grep ${{inputs.upload_prefix}} | xargs -I{} mv {} ${{ inputs.upload_prefix }}-production/
        cp *latest*.yml ${{ inputs.upload_prefix }}-production/
        cp builder-debug.yml ${{ inputs.upload_prefix }}-production/
      shell: bash
      working-directory: ./release/

    - name: Artefact files
      run: ls ${{ inputs.upload_prefix }}-production/
      shell: bash
      working-directory: ./release/

    - name: Upload Production Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.upload_prefix }}-production
        path: release
