# This script will run tests anytime a pull request is added
name: Session Test

on:
  pull_request:
    branches:
      - clearnet
      - unstable

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, macos-11, ubuntu-20.04]
    env:
      SIGNAL_ENV: production
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: git config --global core.autocrlf false

      - name: Checkout git repo
        uses: actions/checkout@v3

      # we stay on v2 even if there is a v3 because the v3 logic is less flexible for our usecase
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Cache Desktop node_modules
        id: cache-desktop-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json', 'yarn.lock', 'patches/**') }}

      #Not having this will break the windows build because the PATH won't be set by msbuild.
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
        if: runner.os == 'Windows'

      - name: Setup node for windows
        if: runner.os == 'Windows'
        run: |
          npm install --global node-gyp@latest
          npm config set msvs_version 2022

      - name: Install Desktop node_modules
        if: steps.cache-desktop-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --network-timeout 600000 --force

      - name: Generate and concat files
        run: yarn build-everything

      - name: Lint Files
        # no need to lint files on all platforms. Just do it once on the quicker one
        if: runner.os == 'Linux'
        run: yarn lint-full

      - name: Unit Test
        run: yarn test
